version: "2.1"

# Docker compose config for development server
services:
  web:
    image: django-test
    build: ./mysite/
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings.dev
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./mysite/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
