version: "2.1"

services:
  django:
    image: django-test
    build: .
    command: sh -c "cd mysite python3 manage.py migrate && python3 manage.py collectstatic --no-input && gunicorn mysite.wsgi -b 0.0.0.0:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings.prod
    ports:
      - 8000:8000
