version: "2.1"

# Docker compose config for production
services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/var/django/static/
    depends_on:
      - web
  web:
    image: django-test
    build: ./mysite/
    command: sh -c "python3 manage.py migrate && python3 manage.py collectstatic --no-input && gunicorn mysite.wsgi -b 0.0.0.0:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings.prod
      - POSTGRES_HOST=db
    volumes:
      - static:/static
    ports:
      - 8000:8000
  db:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
  static:
