# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: production
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - node-dependencies-

      - run:
          name: install node dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: run webpack
          command: npm run build

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - mysite
  test:
    docker:
      - image: circleci/python:3.8
        environment:
          DJANGO_SETTINGS_MODULE: mysite.settings.prod
          DJANGO_SECRET_KEY: secret_key_circle
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_DB: circle_test
          POSTGRES_USER: postgres
      - image: circleci/postgres:10
    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: /tmp/workspace

      # Download and cache dependencies
      - restore_cache:
          keys:
            - python-dependencies-{{ checksum "mysite/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - python-dependencies-

      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r mysite/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: python-dependencies-{{ checksum "mysite/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python mysite/manage.py test polls

      - store_artifacts:
          path: test-reports
          destination: test-reports
